### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by jaraco**
I cherrypicked each of these commits from the fork-googlevoice project in my fork of this repo. These commits represent much of the refactoring and troubleshooting I did in 2014 prior to the 1.0 release of the [googlevoice](https://pypi.org/project/googlevoice) project.

I've tried to reconcile these changes and incorporate them upstream and eventually remove the googlevoice project.

Each of the changes below attempts to be stable, meaning ideally the library should work between each commit. In practice, that's not the case and in fact some like 65a597e94806 include changes intended for the prior commit. Due to the large number, they're probably best reviewed in order.

I do believe this code to be largely functional however, as I used these changes for my own use.

I no longer have a google voice account so I'm not sure how I could test these changes, but I'd very much like to see them incorporated as I'll have a very difficult time supporting the library without actively using it.

Please have a look and let me know what you think. Can they be accepted as-is (even if there are emergent issues)? Would someone be willing to test and work through any issues? Is there a way I can test without setting up a GV account?

Thanks and Regards,
Jason

### CODE REVIEW

**Comment by chris001** [comment]
> Would someone be willing to test and work through any issues? 
I have a fork of this repo which I'm planning to drastically update when I get time hopefully soon.
> Is there a way I can test without setting up a GV account?
I suppose I or someone could lend you a spare testing purposes GV account. This makes me wonder, and so if you don't mind my asking, why do you no longer have a GV account ? Sorry to ask, you don't have to say if you don't want to.

**Comment by jaraco** [comment]
> why do you no longer have a GV account

I originally signed up with a GV account so that my number, its voicemails, etc would be available across carriers. I also wanted to be able to send/receive messages from my PC.

But because it's a proxy, it makes it difficult to originate calls and messages from that number. You also don't get many of the features built into the phone platform.

In addition, the mobile providers added enhanced support for voicemail retrieval and storage (don't have to call to listen) and the Apple ecosystem to which I switched added elegant handoff of SMS and phone calls. All of this made Google Voice more of an impediment than a feature.

**Comment by jaraco** [comment]
I have good news. In order to have more confidence in these changes, I created a GV account and ran some tests and found many bugs in my fork. Where possible, I first implemented those fixes here in this PR, so I now have high confidence in these changes (they work and many tests pass in jaraco/googlevoice).

Unfortunately, due to the approach I took, many of the changes and their associated bugfixes are not in adjacent commits, so many of these commits will not be cherry-pickable. It sure would be nice to incorporate these fixes, though, as even the master of pygooglevoice doesn't run under Python 3.

**Comment by pettazz** [comment]
👍

**Comment by jaraco** [comment]
Huge thanks @pettazz for merging these changes! I'll continue to work to remove the differences in implementation between my fork and this project. Let me know if you have any thoughts on merging the projects.

**Pull request merged**
