### PR TITLE
Implemented solution proposed by ilanZeek to fix Issue #15

### PR DESCRIPTION
**Pull request by twbarber**
Attribute Error: 'NoneType' object has no attribute 'group'

### CODE REVIEW

**Comment by pettazz** [comment]
neat

**Comment by twbarber** [comment]
@illgitthat @pettazz Pull request submitted to fix typo. Tested, able to login and send SMS.

**Comment by illgitthat** [comment]
@twbarber thanks so much - any ideas why I'm still getting this error below?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/webapps/virtualenvs/scraper-env/lib/python2.6/site-packages/googlevoice/voice.py", line 78, in login
    if result.geturl().startswith(getattr(settings, "SMSAUTH")):
AttributeError: 'module' object has no attribute 'SMSAUTH'
```

**Comment by twbarber** [comment]
Could be a couple things. Are you using my most recently updated branch? If so, what action are you trying to do? I can debug from there. Let me enable 2FA on my account, it looks like that's what's going on.

**Comment by illgitthat** [comment]
I don't have two factor auth enabled but I think this version has other
changes besides voice.py I was updating from google code version. I will
update fully to this version in a bit and let you know if I'm still
experiencing any problems with some more info.

Really appreciate the help with this!

On Thu, Dec 10, 2015 at 6:55 PM Tyler Barber <notifications@github.com>
wrote:

> Could be a couple things. Are you using my most recently updated branch?
> If so, what action are you trying to do? I can debug from there. Let me
> enable 2FA on my account, it looks like that's what's going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pettazz/pygooglevoice/pull/16#issuecomment-163790088>.
>
-- 
Adam Bloom

**Comment by twbarber** [comment]
That'll do it. I believe the GCode repo is super outdated. My change is available [here](https://github.com/twbarber/pygooglevoice/tree/issue_15) if you get around to updating before @pettazz merges the change in. Glad I could help.

**Pull request merged**
